mode:
  develop: true
server:
  port: 8090

db:
  dns: "thomas:huan1122@tcp(127.0.0.1:3306)/currency_exchange?charset=utf8mb4&parseTime=True&loc=Local"
  maxIdleConns: 10
  maxOpenConns: 100

redis:
  url: localhost:6379

jwt:
  tokenExpire: 30 # token expire (minutes)
  secretKey: "qwerqw"

ansible:
  user:
    name: root
    password: pass123
  ShutdownHost:
    Args: "`cat \"hello\" >> /hello.txt`"

log:
  MaxSize: 1
  MaxBackups: 10
  MaxAge: 30