info:
  contact: {}
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.1"
paths:
  /api/v1/public/user/login:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: login success
          schema:
            type: string
        "401":
          description: login fail
          schema:
            type: string
      summary: login
      tags:
      - User Api
swagger: "2.0"
